Exploratory Data Analysis of Extended Hospitalizations Compared to Average Stays

Sources from New York State Department of Health in the years 2015 and 2021

Packages to be imported and retrieving data

In [106]:
import pandas as pd 
import sqlite3
from sodapy import Socrata

In [ ]:
# use Socrata to retrieve data for years 2015 and 2021

# no username or password because of public data
client1 = Socrata("health.data.ny.gov", None)

# First 10,000 results, returned as JSON from API / converted to Python list of dictionaries by sodapy.
results1 = client1.get("82xm-y6g8", limit=10000)

# Convert to pandas DataFrame
healthcare_2015 = pd.DataFrame.from_records(results1)
healthcare_2015.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

,hospital_service_area,hospital_county,operating_certificate_number,permanent_facility_id,facility_name,age_group,zip_code_3_digits,gender,race,ethnicity,...,apr_risk_of_mortality,apr_medical_surgical_description,payment_typology_1,payment_typology_2,birth_weight,abortion_edit_indicator,emergency_department_indicator,total_charges,total_costs,payment_typology_3
0,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,70 or Older,147,F,White,Not Span/Hispanic,...,Minor,Medical,Medicare,Private Health Insurance,0,N,Y,5333.90,4818.42,NaN
1,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,70 or Older,147,F,White,Not Span/Hispanic,...,Moderate,Medical,Medicare,NaN,0,N,Y,4865.99,4588.78,NaN
2,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,70 or Older,147,F,White,Not Span/Hispanic,...,Minor,Medical,Medicare,Private Health Insurance,0,N,Y,5901.54,5559.56,NaN
3,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,50 to 69,147,F,White,Not Span/Hispanic,...,Minor,Medical,Medicare,NaN,0,N,Y,3619.08,3567.25,NaN
4,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,70 or Older,147,M,White,Not Span/Hispanic,...,Moderate,Medical,Medicare,Blue Cross/Blue Shield,0,N,Y,3185.87,3167.89,Private Health Insurance

In [108]:
# Use same process for data from 2021
client2 = Socrata("health.data.ny.gov", None)
results2 = client2.get("tg3i-cinn", limit=10000)
healthcare_2021 = pd.DataFrame.from_records(results2)
healthcare_2021.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

,hospital_service_area,hospital_county,operating_certificate_number,permanent_facility_id,facility_name,age_group,zip_code_3_digits,gender,race,ethnicity,...,apr_severity_of_illness,apr_risk_of_mortality,apr_medical_surgical,payment_typology_1,payment_typology_2,emergency_department_indicator,total_charges,total_costs,birth_weight,payment_typology_3
0,New York City,Bronx,7000006,001169,Montefiore Medical Center - Henry & Lucy Moses...,70 or Older,104,M,Other Race,Spanish/Hispanic,...,Major,Extreme,Medical,Medicare,Medicaid,Y,320922.43,60241.34,NaN,NaN
1,New York City,Bronx,7000006,001169,Montefiore Medical Center - Henry & Lucy Moses...,50 to 69,104,F,White,Not Span/Hispanic,...,Moderate,Minor,Medical,Private Health Insurance,NaN,Y,61665.22,9180.69,NaN,NaN
2,New York City,Bronx,7000006,001168,Montefiore Medical Center-Wakefield Hospital,18 to 29,104,F,Other Race,Spanish/Hispanic,...,Minor,Minor,Surgical,Medicaid,NaN,N,42705.34,11366.50,NaN,NaN
3,New York City,Bronx,7000006,003058,Montefiore Med Center - Jack D Weiler Hosp of ...,70 or Older,104,M,Other Race,Spanish/Hispanic,...,Major,Major,Medical,Medicare,Medicaid,Y,72700.17,12111.75,NaN,NaN
4,New York City,Bronx,7000006,001169,Montefiore Medical Center - Henry & Lucy Moses...,50 to 69,104,F,Black/African American,Not Span/Hispanic,...,Moderate,Minor,Medical,Medicare,Medicaid,Y,55562.51,8339.72,NaN,NaN

Concatenating Years 2015 and 2021

In [ ]:
# join both years into one table
healthcare = pd.concat([healthcare_2015, healthcare_2021], axis=0, ignore_index=True)

# combine columns with matching information but different column headers
healthcare['Diagnosis'] = healthcare['ccsr_diagnosis_description'].fillna(healthcare['ccs_diagnosis_description'])
healthcare['Diagnosis Code'] = healthcare['ccsr_diagnosis_code'].fillna(healthcare['ccs_diagnosis_code'])
healthcare['Procedure Description'] = healthcare['ccsr_procedure_code'].fillna(healthcare['ccs_procedure_description'])
healthcare.head()

,hospital_service_area,hospital_county,operating_certificate_number,permanent_facility_id,facility_name,age_group,zip_code_3_digits,gender,race,ethnicity,...,payment_typology_3,ccsr_diagnosis_code,ccsr_diagnosis_description,ccsr_procedure_code,ccsr_procedure_description,apr_severity_of_illness,apr_medical_surgical,Diagnosis,Diagnosis Code,Procedure Description
0,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,70 or Older,147,F,White,Not Span/Hispanic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pneumonia (except that caused by tuberculosis ...,122,NO PROC
1,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,70 or Older,147,F,White,Not Span/Hispanic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fluid and electrolyte disorders,55,NO PROC
2,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,70 or Older,147,F,White,Not Span/Hispanic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pneumonia (except that caused by tuberculosis ...,122,ELECTROCARDIOGRAM
3,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,50 to 69,147,F,White,Not Span/Hispanic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fluid and electrolyte disorders,55,NO PROC
4,Western NY,Allegany,0226700,37,Cuba Memorial Hospital Inc,70 or Older,147,M,White,Not Span/Hispanic,...,Private Health Insurance,NaN,NaN,NaN,NaN,NaN,NaN,Pneumonia (except that caused by tuberculosis ...,122,NO PROC

Data Cleaning

The nature of healthcare data is often an overwhelming wealth of information. Many columns were removed to maintain the focus on primary objectives. The columns with numerical values are then coded to be read as such.

In [110]:
# drop columns not needed
healthcare = healthcare.drop(columns = [
    'hospital_service_area', 'hospital_county', 'operating_certificate_number', 'permanent_facility_id', 'facility_name', 
    'zip_code_3_digits', 'patient_disposition',  'discharge_year', 'ccs_diagnosis_description', 'ccs_diagnosis_code', 'ccs_procedure_code', 'ccs_procedure_description', 
    'apr_drg_code', 'apr_drg_description', 'apr_mdc_code', 'apr_mdc_description', 'apr_severity_of_illness_code', 'apr_severity_of_illness_description', 
    'apr_risk_of_mortality', 'apr_medical_surgical_description', 'payment_typology_1', 'payment_typology_2', 'payment_typology_3', 'birth_weight', 
    'abortion_edit_indicator', 'emergency_department_indicator', 'ccsr_diagnosis_code', 'ccsr_diagnosis_description', 'ccsr_procedure_code', 
    'ccsr_procedure_description', 'Diagnosis Code', 'Procedure Description', 'apr_severity_of_illness', 'apr_medical_surgical'
    ])
healthcare.head()

,age_group,gender,race,ethnicity,length_of_stay,type_of_admission,total_charges,total_costs,Diagnosis
0,70 or Older,F,White,Not Span/Hispanic,4,Urgent,5333.90,4818.42,Pneumonia (except that caused by tuberculosis ...
1,70 or Older,F,White,Not Span/Hispanic,4,Elective,4865.99,4588.78,Fluid and electrolyte disorders
2,70 or Older,F,White,Not Span/Hispanic,4,Urgent,5901.54,5559.56,Pneumonia (except that caused by tuberculosis ...
3,50 to 69,F,White,Not Span/Hispanic,2,Elective,3619.08,3567.25,Fluid and electrolyte disorders
4,70 or Older,M,White,Not Span/Hispanic,2,Elective,3185.87,3167.89,Pneumonia (except that caused by tuberculosis ...

In [111]:
# check for null
healthcare.isnull().sum()

age_group            0
gender               0
race                 0
ethnicity            0
length_of_stay       0
type_of_admission    0
total_charges        0
total_costs          0
Diagnosis            0
dtype: int64

In [112]:
# identify and delete duplicate entries
duplicates = healthcare.duplicated()
healthcare.drop_duplicates()

,age_group,gender,race,ethnicity,length_of_stay,type_of_admission,total_charges,total_costs,Diagnosis
0,70 or Older,F,White,Not Span/Hispanic,4,Urgent,5333.90,4818.42,Pneumonia (except that caused by tuberculosis ...
1,70 or Older,F,White,Not Span/Hispanic,4,Elective,4865.99,4588.78,Fluid and electrolyte disorders
2,70 or Older,F,White,Not Span/Hispanic,4,Urgent,5901.54,5559.56,Pneumonia (except that caused by tuberculosis ...
3,50 to 69,F,White,Not Span/Hispanic,2,Elective,3619.08,3567.25,Fluid and electrolyte disorders
4,70 or Older,M,White,Not Span/Hispanic,2,Elective,3185.87,3167.89,Pneumonia (except that caused by tuberculosis ...
...,...,...,...,...,...,...,...,...,...
19995,70 or Older,F,Black/African American,Not Span/Hispanic,3,Emergency,24384.98,16620.53,Fluid and electrolyte disorders
19996,70 or Older,F,Other Race,Spanish/Hispanic,21,Emergency,159605.70,108785.49,COVID-19
19997,18 to 29,F,Black/African American,Not Span/Hispanic,2,Emergency,10690.28,7286.38,Early or threatened labor
19998,70 or Older,M,Other Race,Spanish/Hispanic,1,Emergency,16474.38,11228.76,Cerebral infarction
19999,50 to 69,F,Black/African American,Not Span/Hispanic,2,Urgent,13671.18,7862.08,Acute myocardial infarction

In [113]:
# since the column length_of_stay, total_costs, and total_charges are currently being read by python as a string, 
# convert the columns to read as numeric values and replace errors as NaN
healthcare['length_of_stay'] = pd.to_numeric(healthcare['length_of_stay'], errors='coerce')
healthcare['total_costs'] = pd.to_numeric(healthcare['total_costs'], errors='coerce')
healthcare['total_charges'] = pd.to_numeric(healthcare['total_charges'], errors='coerce')

In [114]:
# after looking at the data and some options for analysis, a charge to coat ratio would be interesting 
healthcare['Charge to Cost Ratio'] = healthcare['total_charges'] / healthcare['total_costs']
healthcare.head()

,age_group,gender,race,ethnicity,length_of_stay,type_of_admission,total_charges,total_costs,Diagnosis,Charge to Cost Ratio
0,70 or Older,F,White,Not Span/Hispanic,4.0,Urgent,5333.90,4818.42,Pneumonia (except that caused by tuberculosis ...,1.106981
1,70 or Older,F,White,Not Span/Hispanic,4.0,Elective,4865.99,4588.78,Fluid and electrolyte disorders,1.060410
2,70 or Older,F,White,Not Span/Hispanic,4.0,Urgent,5901.54,5559.56,Pneumonia (except that caused by tuberculosis ...,1.061512
3,50 to 69,F,White,Not Span/Hispanic,2.0,Elective,3619.08,3567.25,Fluid and electrolyte disorders,1.014529
4,70 or Older,M,White,Not Span/Hispanic,2.0,Elective,3185.87,3167.89,Pneumonia (except that caused by tuberculosis ...,1.005676

Create a dataset with 'average' hospital stay information and filter out most prevalent diagnoses not relevant to the analysis

In [115]:
# to compare data on the average length of stay vs an extended stay, create two sets of data: one that 
# reflects the average according to research (4.6 is average; will include both 4 and 5 days), and one
# that is greater than or equal to 21 days 
avg_stay = healthcare[healthcare['length_of_stay'].isin([4, 5])]
avg_stay.head()

,age_group,gender,race,ethnicity,length_of_stay,type_of_admission,total_charges,total_costs,Diagnosis,Charge to Cost Ratio
0,70 or Older,F,White,Not Span/Hispanic,4.0,Urgent,5333.90,4818.42,Pneumonia (except that caused by tuberculosis ...,1.106981
1,70 or Older,F,White,Not Span/Hispanic,4.0,Elective,4865.99,4588.78,Fluid and electrolyte disorders,1.060410
2,70 or Older,F,White,Not Span/Hispanic,4.0,Urgent,5901.54,5559.56,Pneumonia (except that caused by tuberculosis ...,1.061512
6,70 or Older,F,White,Not Span/Hispanic,4.0,Urgent,5338.93,4929.92,Pneumonia (except that caused by tuberculosis ...,1.082965
7,70 or Older,F,White,Not Span/Hispanic,4.0,Elective,4870.70,4304.78,Diverticulosis and diverticulitis,1.131463

In [116]:
# since the aim of this project is more for identifying characteristics/demographics of patients prior to 
# admission, which is not information known or relevant for newborns, the 'liveborn' diagnosis is also edited out
avg_stay = avg_stay[~avg_stay['Diagnosis'].str.contains('liveborn', case=False)]

In [117]:
# find most common diagnoses for an average stay
avg_stay['Diagnosis'].value_counts()

Diagnosis
Septicemia (except in labor)                                                       196
Chronic obstructive pulmonary disease and bronchiectasis                           185
COVID-19                                                                           158
Pneumonia (except that caused by tuberculosis or sexually transmitted disease)     128
Congestive heart failure; nonhypertensive                                          112
                                                                                  ...
E Codes: Unclassified                                                                1
Fetopelvic disproportion; obstruction                                                1
Screening and history of mental health and substance abuse codes                     1
Meningitis (except that caused by tuberculosis or sexually transmitted disease)      1
Nutritional deficiencies                                                             1
Name: count, Length: 302, dtype: int64

In [118]:
# Save the finalized data to a CSV for analysis and visualization on Tableau
avg_stay.to_csv('average_hospitalizations.csv')

Create a dataset with 'extended' hospital stay information and filter out most prevalent diagnoses not relevant to the analysis

In [119]:
# to focus on extended hospitalizations, edit the length of stay to greater than or equal to 21 days
ext_stay = healthcare[healthcare['length_of_stay'] >= 21]
ext_stay.head()
ext_stay.tail()

,age_group,gender,race,ethnicity,length_of_stay,type_of_admission,total_charges,total_costs,Diagnosis,Charge to Cost Ratio
19916,18 to 29,F,Other Race,Spanish/Hispanic,27.0,Emergency,250255.45,143917.91,Septicemia,1.738876
19927,0 to 17,F,Black/African American,Not Span/Hispanic,55.0,Emergency,221292.58,127261.82,Schizophrenia spectrum and other psychotic dis...,1.738876
19976,70 or Older,M,Other Race,Spanish/Hispanic,32.0,Emergency,128238.07,73747.66,Schizophrenia spectrum and other psychotic dis...,1.738876
19990,50 to 69,M,Black/African American,Not Span/Hispanic,23.0,Emergency,169918.76,97717.56,Nonspecific chest pain,1.738876
19996,70 or Older,F,Other Race,Spanish/Hispanic,21.0,Emergency,159605.70,108785.49,COVID-19,1.467160

In [120]:
# find most common diagonses among extended hospital stay
ext_stay['Diagnosis'].value_counts()

Diagnosis
Schizophrenia spectrum and other psychotic disorders          118
Septicemia                                                     81
COVID-19                                                       36
Liveborn                                                       27
Septicemia (except in labor)                                   22
                                                             ...
Skin and subcutaneous tissue infections                         1
Pancreatic disorders (excluding diabetes)                       1
Encounter for antineoplastic therapies                          1
Hypertension with complications and secondary hypertension      1
Nonspecific chest pain                                          1
Name: count, Length: 118, dtype: int64

In [121]:
# because psychiatric hospitalizations are not the focus and differ from other medical stays, they are edited out here
# using key words in Diagnosis column (ideally, there would have been ICD codes, but it is not used in this data)
psychiatric_keywords = ['depression', 'depressive', 'schizophrenia', 'anxiety', 'bipolar', 'psychosis', 'psychotic', 'mood']
ext_stay_no_psychiatric = ext_stay[~ext_stay['Diagnosis'].str.contains('|'.join(psychiatric_keywords), case=False)]
ext_stay_no_psychiatric['Diagnosis'].value_counts().head(10)

Diagnosis
Septicemia                                                                   81
COVID-19                                                                     36
Liveborn                                                                     27
Septicemia (except in labor)                                                 22
Respiratory failure; insufficiency; arrest                                    8
Sequela of cerebral infarction and other cerebrovascular disease              7
Complication of other surgical or medical care, injury, initial encounter     7
Acute and unspecified renal failure                                           7
Heart failure                                                                 6
Cardiac dysrhythmias                                                          5
Name: count, dtype: int64

In [122]:
# since the aim of this project is more for identifying characteristics/demographics of patients prior to 
# admission, which is not information known or relevant for newborns, the 'liveborn' diagnosis is also edited out
ext_stay_no_liveborn = ext_stay_no_psychiatric[~ext_stay_no_psychiatric['Diagnosis'].str.contains('liveborn', case=False)]

# since the variable names are becoming cumbersome
hospitalizations = ext_stay_no_liveborn
hospitalizations['Diagnosis'].value_counts().head(10)

Diagnosis
Septicemia                                                                   81
COVID-19                                                                     36
Septicemia (except in labor)                                                 22
Respiratory failure; insufficiency; arrest                                    8
Sequela of cerebral infarction and other cerebrovascular disease              7
Acute and unspecified renal failure                                           7
Complication of other surgical or medical care, injury, initial encounter     7
Heart failure                                                                 6
Urinary tract infections                                                      5
Cardiac dysrhythmias                                                          5
Name: count, dtype: int64

In [123]:
# Save the finalized data to a CSV for analysis and visualization on Tableau
hospitalizations.to_csv('extended_hospitalizations.csv')
hospitalizations.head()

,age_group,gender,race,ethnicity,length_of_stay,type_of_admission,total_charges,total_costs,Diagnosis,Charge to Cost Ratio
227,70 or Older,M,White,Not Span/Hispanic,26.0,Emergency,114991.25,74547.18,Gastrointestinal hemorrhage,1.542530
303,70 or Older,M,White,Not Span/Hispanic,22.0,Emergency,68685.75,38791.06,Septicemia (except in labor),1.770659
311,70 or Older,M,White,Not Span/Hispanic,21.0,Emergency,110274.50,68240.75,Septicemia (except in labor),1.615963
408,50 to 69,F,White,Not Span/Hispanic,31.0,Elective,157154.40,75850.15,Cancer of colon,2.071906
451,50 to 69,F,White,Not Span/Hispanic,22.0,Emergency,84974.50,45275.51,Septicemia (except in labor),1.876831

In [ ]:
# upon trial and error with Tableau, I want to be able to have my dashboard use a filter to compare average
# to extended hospitalizations. So I am going to join the two tables here 
avg_and_extended = pd.concat([hospitalizations, avg_stay])

# just checking to make sure it looks correct 
avg_and_extended. head()
avg_and_extended.tail()

,age_group,gender,race,ethnicity,length_of_stay,type_of_admission,total_charges,total_costs,Diagnosis,Charge to Cost Ratio
19970,30 to 49,F,White,Not Span/Hispanic,4.0,Emergency,33820.01,19449.35,Maternal care related to fetal conditions,1.738876
19984,70 or Older,M,Other Race,Spanish/Hispanic,4.0,Emergency,65455.36,30423.39,COVID-19,2.151481
19991,30 to 49,F,Other Race,Spanish/Hispanic,4.0,Emergency,47873.75,22251.53,Previous C-section,2.151481
19993,30 to 49,M,Other Race,Spanish/Hispanic,4.0,Emergency,38572.37,17928.28,"Traumatic brain injury (TBI); concussion, init...",2.151482
19994,70 or Older,M,Other Race,Unknown,4.0,Urgent,27849.65,16015.89,Neoplasms of unspecified nature or uncertain b...,1.738876

In [127]:
avg_and_extended.to_csv('avg_and_extended_hospitalizations.csv')